version: "1.0"
stages:
  - "stage 1"
  - "stage 2"
  - "stage 3"
  - "parallel stage"
steps:
  hello:
    stage: stage 1
    image: node
    commands:
    - echo "Hello Step 1!"
  world:
    type: parallel
    stage: parallel stage
    steps:
      google_nick:
        image: node
        title: Helo Google
        commands:
        - echo "Hello Step 11!"
      azure_test:
        image: node
        commands:
        - echo "Hello Step 12!"
      dockerhub_test:
        image: node
        commands:
        - echo "Hello Step 13!"
      jfrog_test:
        image: node
        commands:
        - echo "Hello Step 14!"
  BuildingDockerImage:
    stage: stage 2
    title: Building Docker Image
    type: build
    image_name: vmechkauskas-codefresh/cf-canary-percentage
    working_directory: "./"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile:
      content: '
       #FROM node:8.0-alpine AS builder
       FROM 192.168.99.100:5000/vmechkauskas-codefresh/vmechkauskas-codefresh/cf-canary-percentage-env-image:master

       # installing all needed tools and libs
       # RUN apt-get update
       # RUN apt-get install git -y --force-yes
       # RUN apt-get install -y --force-yes nodejs
       # RUN apt-get install -y --force-yes npm
       # RUN apt-get install wget -y --force-yes
       # RUN apt-get install -y --force-yes nodejs-legacy
       RUN npm install n -g
       #RUN n 10.13.0
       RUN n 9.6.1

       #install project dependencies
       RUN npm install -g gulp@3.9.1
       RUN npm install -g bower

       WORKDIR /app

       ADD ./ /app

       # Copying application code
       #COPY . /app

       # Installing all dependencies
       RUN npm install && bower install --allow-root

       # CMD npm build

       RUN gulp build-prod

       EXPOSE 9000

       CMD ["gulp", "serve"]

       # CMD ["gulp ${{GULP_COMMAND}}"]
      '
  

